spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learningdocs
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: always
  port: 8080